#!/root/ansible/myansible/bin/handlers-notifiers
#here use of handler is demonstrated , used for tasks with dependency
#handler name should be present in notifier for the handler to be run , it can handle multiple handlers.
- name: Installing WebServer
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  tasks:
    - name: Ensure Apache is at the Latest Version
      yum:
        name: httpd
        state: present
      notify:
        - Ensure Apache is Running
        - Ensure Apache restart 

  handlers:
    - name: Ensure Apache is Running
      service:
        name: httpd
        state: started

    - name: Ensure Apache restart
      service:
        name: httpd
        state: restarted
