#!/root/ansible/myansible/bin/handlers-notifiers
#sample to check if httpd is installed or not using when statement and changed keyword.
#this will give the output as true or false if the httpd is already installed or not
- name: Installing WebServer
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  tasks:
    - name: Ensure Apache is at the Latest Version
      yum:
        name: httpd
        state: present
      register: httpd_installation_status


    - name: Ensure Apache is Running
      service:
        name: httpd
        state: started
      when: httpd_installation_status.changed == True 
