---
- name: Schedule a weekly log cleanup
  hosts: all  # This play runs on all specified hosts
  become: yes  # Use privilege escalation (run as root)

  tasks:
    - name: Ensure the log cleanup script exists
      copy:
        src: cleanup_logs.sh  # Local path to the script (should be in the same directory as the playbook or relative to it)
        dest: /usr/local/bin/cleanup_logs.sh  # Path where the script will be copied on the remote system
        mode: '0755'  # Sets the file permission to be executable (rwxr-xr-x)

    # This task sets up a cron job to execute the script weekly
    - name: Schedule a weekly log cleanup
      cron:
        name: "Weekly Log Cleanup"  # Description of the cron job (used as an identifier)
        minute: "30"  # The script will run at minute 30
        hour: "3"  # At 3 AM
        day: "*"  # Every day of the month
        month: "*"  # Every month
        weekday: "1"  # Only on Mondays (0 = Sunday, 1 = Monday, etc.)
        job: "/usr/local/bin/cleanup_logs.sh"  # The command/script to execute
        user: "root"  # User that will run the job (needs permissions)


